SHELL=/bin/bash

ifeq ($(strip $(QLAT_PREFIX)),)
	QLAT_PREFIX=$(shell readlink -m "$$HOME/qlat-build/default")
endif

include $(QLAT_PREFIX)/include/qlat/Makefile.inc

all: qlat.x

run: qlat.x
	time mpirun --oversubscribe -x OMP_NUM_THREADS=2 --np 8 ./qlat.x | tee log

qlat.x: *.C
	time make build
	[ -f $@ ]

build:
	-time $(MPICXX) $(CXXFLAGS) $(LDFLAGS) -o qlat.x *.C $(LIBS) 2>&1 | grep --color=always 'error:\|'

show-info:
	@echo MPICXX: $(MPICXX)
	@echo CXXFLAGS: $(CXXFLAGS)
	@echo LDFLAGS: $(LDFLAGS)
	@echo LIBS: $(LIBS)

clean:
	-rm qlat.x
	-rm log.full
	-rm -rf results*
	-rm -rf huge-data

run-test: qlat.x
	echo > log
	time mpirun --oversubscribe -x OMP_NUM_THREADS=2 --np 8 ./qlat.x | tee log.full
	cat log.full | grep -v '^Timer\|^check_status:\|^display_geo_node : id_node =' > log
	make diff | cat
	# make clean

diff:
	-git diff log

dist-clean: clean
	-git checkout log
