SHELL=/bin/bash

CC=mpicc -fopenmp -O2 -Wall
CXX=mpic++ -std=c++0x -fopenmp -O2 -Wall

qlat_prefix=$$HOME/qlat-build/1.0

QLAT_INCLUDE=$(qlat_prefix)/include
QLAT_LIB=$(qlat_prefix)/lib

QLAT_CFLAGS=-fno-strict-aliasing -DEIGEN_DONT_ALIGN_STATICALLY
QLAT_CFLAGS+= -I$(QLAT_INCLUDE)
QLAT_CFLAGS+= -I$(QLAT_INCLUDE)/eigen3
QLAT_CFLAGS+= -I$(QLAT_INCLUDE)/utils

QLAT_CXXFLAGS=$(QLAT_CFLAGS)

QLAT_LDFLAGS=-L$(QLAT_LIB)
QLAT_LDFLAGS+= -lgsl -lgslcblas -lm
QLAT_LDFLAGS+= -lfftw3_omp -lfftw3
QLAT_LDFLAGS+= -lz

all: qlat.x

run: qlat.x
	. $(qlat_prefix)/setenv.sh ; time mpirun -x OMP_NUM_THREADS=2 --np 4 ./qlat.x
	# make clean

qlat.x: *.C
	. $(qlat_prefix)/setenv.sh ; time make build
	[ -f $@ ]

build:
	-$(CXX) -o qlat.x $(QLAT_CXXFLAGS) *.C $(QLAT_LDFLAGS) 2>&1 | grep --color=always 'error:\|'

clean:
	-rm qlat.x
	-rm -rf huge-data

show-info:
	@echo CXX: $(CXX)
	@echo CXXFLAGS: $(QLAT_CXXFLAGS)
	@echo LDFLAGS: $(QLAT_LDFLAGS)
