#!/usr/bin/env python3
#
# Author: Christoph Lehner 2021
# Author: Luchang Jin 2021

import gpt as g
import qlat as q
import qlat_gpt as qg
import sys

qg.begin_with_gpt()

# Parameters
path = g.default.get("--path", None)

if path is None:
    g.message("Need to provide path via --path path")
    sys.exit(1)

q.check_compressed_eigen_vectors(path)

q.timer_display()

qg.end_with_gpt()
