#!/bin/bash

# See https://github.com/lehner/gpt/blob/master/lib/cgpt/update
# Original author Christoph Lehner

# configure warning
WARNING="This file is automatically generated, do not modify!"

# Automatically generate list of exported functions
export LC_ALL=C
(
    echo "// ${WARNING}"
    sed -n 's/EXPORT(\([^,]*\),.*/EXPORT_FUNCTION(\1)/p' *.cpp | sort
) > exports.h.template.new

for f in "$@" ; do
    cat "$f" >> exports.h.template.new
done

if [ -f exports.h.template ] && diff exports.h.template.new exports.h.template ; then
    echo No update for exports.h.template
    rm exports.h.template.new
else
    echo Update exports.h.template
    mv exports.h.template.new exports.h.template
fi

echo "  Found $(grep -c EXPORT exports.h.template) exported functions"
echo "================================================================================"
