#!/usr/bin/env python3
#
# Author: Luchang Jin 2021

import qlat as q
import sys

q.begin()

# Usage: eigen-system-checksum path1 path2 ...

for path in sys.argv[1:]:
    q.check_compressed_eigen_vectors(path)

q.timer_display()

q.end()
