#!/usr/bin/env python3

import sys
import qlat as q
import gpt as g
import numpy as np

import qlat_gpt as qg

size_node_list = [
        [1, 1, 1, 1],
        [1, 1, 1, 2],
        [1, 1, 1, 4],
        [1, 1, 1, 8],
        [2, 2, 2, 2],
        [2, 2, 2, 4],
        ]

# q.begin(sys.argv, size_node_list)

qg.begin_with_gpt()

p_source = g.default.get("--source", None)
p_output = g.default.get("--output", None)

def load():
    if p_source is None:
        g.message("Need to provide source file with '--source filename'. Use a sample gauge field for now.")
        total_site = [ 4, 4, 4, 8, ]
        geo = q.Geometry(total_site, 1)
        gf = q.GaugeField(geo)
        rs = q.RngState("seed")
        gf.set_rand(rs.split("gf-init"), 0.5, 10)
    else:
        gf = q.GaugeField()
        gf.load(p_source)
        # gf = qg.load_gauge_field(p_source)
    return gf

gf = load()

topo_list = q.smear_measure_topo(gf)

if p_output is not None:
    q.save_pickle_obj(topo_list, p_output)
else:
    g.message("To save the result, use '--output filename.pickle'. Print to screen for now.")
    q.displayln_info(q.pformat(topo_list))

q.timer_display()

qg.end_with_gpt()
